# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- group: pipeline_variables

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: ssh-add -l
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: $(github_public_key)
    sshPublicKey: $(acurus_ed25519_public_key)
    sshKeySecureFile: 'acurus_ed25519_private_key'

- script: git clone git@github.com:ZENEnergy/zen.terraform.module.azure_front_door_function.git
    
